[upstox]
api_key = "your_api_key"
api_secret = "your_api_secret"
access_token = "your_daily_access_token"

[scanner]
interval = "5minute"
lookback_bars = 100
rsi_period = 14
rsi_oversold = 30
rsi_overbought = 70
