[upstox]
api_key = "f4d5e125-32c8-472e-b72a-f53b8fbaae7a"
api_secret = "bmmz804gjj"
access_token = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0UEM2SEsiLCJqdGkiOiI2OTE5NTc0YzVkNjFkNDRlYWI2MTZjNTAiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc2MzI2ODQyOCwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzYzMzMwNDAwfQ.Z8KbNQK-glYszkTtL_v6idNhqco2r9o2UP139swIH6c"

[scanner]
interval = "5minute"
lookback_bars = 100
rsi_period = 14
rsi_oversold = 30
rsi_overbought = 70
